[workspace]
members = [ 
    "crates/core/*",  
    "crates/utility/*",
    "crates/runtime", 
]

# 2021エディション用のresolverを設定
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"